version: '3.8'

services:
  backend:
    depends_on:
      - mysql
    build: ./
    container_name: backend
    ports:
      - "8080:8080"
    networks:
      runnershigh:
    restart: always
    tty: true
    environment:
      SPRING_PROFILES_ACTIVE: dev

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: runnershigh
      TZ: Asia/Seoul
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      runnershigh:
volumes:
  mysql_data:

networks:
  runnershigh:

