version: '3.8'

services:
  backend:
    build: ./
    container_name: backend
    ports:
      - "8080:8080"
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: dev
    tty: true
    depends_on:
      - mysql
    networks:
      runnershigh:

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: runnershigh
      MYSQL_ROOT_PASSWORD: 1234
      TZ: Asia/Seoul
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      runnershigh:

volumes:
  mysql_data:

networks:
  runnershigh:
    driver: bridge

