name: Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Load code from GitHub repository
        uses: actions/checkout@v4

      - name: Install JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Make application.yml
        run: echo "${{ secrets.APPLICATION_PROPERTIES }}" > src/main/resources/application-dev.yml

      - name: Build JAR file
        run: ./gradlew clean build

      - name: Change built file name
        run: mv ./build/libs/*SNAPSHOT.jar ./project.jar

      - name: Log in to Docker Hub (GitHub Actions)
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/capstone-hub:latest .

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/capstone-hub:latest

      - name: SSH into AWS EC2 and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_EC2_IP }}
          username: ubuntu
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
            docker compose down || true
            docker compose pull
            docker compose up -d
            sudo docker image prune -f