name: Deloy to GCP

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Load a file from github repository
        uses: actions/checkout@v4

      - name: Install JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Make application.yml
        run: echo "${{secrets.APPLICATION_PROPERTIES}}" > src/main/resources/application.yml

      - name: Build JAR file
        run: ./gradlew clean build

      - name: Build Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-app:latest .

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Push Docker image to GCR
        run: |
          gcloud auth configure-docker
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-app:latest

      - name: SSH into GCP VM and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.GCP_VM_IP }}
          username: ${{ secrets.GCP_VM_USER }}
          key: ${{ secrets.GCP_SSH_KEY }}
          script: |
            cd ~/app
            docker stop my-app || true
            docker rm my-app || true
            docker pull gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-app:latest
            docker run -d --name my-app -p 8080:8080 gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-app:latest